### ISSUE TITLE
Specification Validation Error: The output does not have profile  information in the resource meta profile element. 

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#111]
**Describe the bug**
The FHIR output does not have  profiles in the meta element (except for Bundle) which should mandate the profiles the resource needs to comply to. The profile in the meta is mandatory for profiled resources.
Missing profiles
Patient => https://fhir.hl7.org.uk/STU3/StructureDefinition/CareConnect-Patient-1
Practitioner => https://fhir.hl7.org.uk/STU3/StructureDefinition/CareConnect-Practitioner-1
Organization => https://fhir.hl7.org.uk/STU3/StructureDefinition/CareConnect-Organization-1
Observation => https://fhir.hl7.org.uk/STU3/StructureDefinition/CareConnect-Observation-1
ProcedureRequest => https://fhir.hl7.org.uk/STU3/StructureDefinition/CareConnect-ProcedureRequest-1
DiagnosticReport =>https://fhir.hl7.org.uk/STU3/StructureDefinition/CareConnect-DiagnosticReport-1 

**To reproduce**
1. Send any payload in the mailbox.
2. Get the inbound queue
3. Inspect the payload, there is no profile in the meta element

**Expected behavior**
- the profile should be present.

**Comment by ejudgemeddbase** [comment]
**RETEST 1**
 
**TEST STEPS TO REPRODUCE ISSUE**
I re-ran request multi_pathology.edifact.dat and inspected the FHIR output.

**ACTUAL RESULT**
 
[116Payload.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6746693/116Payload.txt)
![111DiagnosticReport](https://user-images.githubusercontent.com/82526722/124092947-4b910980-da4f-11eb-9758-e94a2922dd6b.PNG)
![111MessageHeader](https://user-images.githubusercontent.com/82526722/124092950-4c29a000-da4f-11eb-8234-065f0ee27c6a.PNG)
![111Observation](https://user-images.githubusercontent.com/82526722/124092951-4c29a000-da4f-11eb-9710-439383015a50.PNG)
![111Organisation](https://user-images.githubusercontent.com/82526722/124092953-4cc23680-da4f-11eb-816e-1c672fa90aa4.PNG)
![111Patient](https://user-images.githubusercontent.com/82526722/124092955-4cc23680-da4f-11eb-8909-ed3769dee64a.PNG)
![111Practitioner](https://user-images.githubusercontent.com/82526722/124092956-4cc23680-da4f-11eb-93c8-b1fcb6518ad4.PNG)
![111ProcedureRequest](https://user-images.githubusercontent.com/82526722/124092957-4cc23680-da4f-11eb-81b7-17f40a8d23c2.PNG)

I can see the Profile tag for Patient, Practitioner, Organization, Observation, ProcedureRequest and DiagnosticReport. 
 
**Retest 1 PASSED**
 
**Defect 111 Closed**
