### ISSUE TITLE
Specification Validation Error: the message specification requires Message Header, but it is missing from current FHIR ouput

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#112]
**Describe the bug**
MessageHeader resource is mandated in the Message specification, but it is missing from the FHIR output.
see diagram in https://developer.nhs.uk/apis/itk3nationalpathology-1-1-0/explore.html

**To reproduce**

1. Send any payload in the mailbox.
2. Get the inbound queue
Inspect the payload, there is no message header in the FHIR output

**Expected behavior **

There should be MessageHeader resources, or if not this should be noted somewhere as a deviation from message specification.

**Comment by bartek-sarul** [comment]
@Kusnaditjung there is a mix up of STU3 and v4 FHIR documentation for Pathology and Screening.
We were told to do STU3 and here https://hscic.kahootz.com/connect.ti/PathologyandDiagnostics/view?objectId=13046960#13046960 you can see that MessageHeader resource is not present.

Is provided lab-results adaptor documentation misleading that v4 is used?

**Comment by Kusnaditjung** [comment]
@bartek-sarul I am not aware of V4 FHIR (do you mean R4 ??)...  my understanding is the specification pages are all STU3... the page you refer to does not necessarily contradict the specification pages which is also referred at the bottom of your pages. MessageHeader is a transport-layer/routing element (replicating ITK element), which does not necessarily appear on the information model of the content. The specification pages mandate the existence of MessageHeader resource here https://developer.nhs.uk/apis/itk3messagedistribution/explore_bundle_overview.html. But if it is explicitly agreed by NHSD to ignore this resource for the adapter work, I think this should be put down in the adapter documentation as an exception to the specification pages ??

**Comment by bartek-sarul** [comment]
@Kusnaditjung yes, by v4 I meant R4. Thank you for explaining the MessageHeader resource purpose. We'll start working on that

**Comment by bartek-sarul** [comment]
Missing value for Screening in https://fhir.nhs.uk/STU3/CodeSystem/ITK-MessageEvent-2 which is needed for https://fhir.nhs.uk/STU3/StructureDefinition/ITK-MessageHeader-2
Need clarification from NHS

**Comment by Kusnaditjung** [comment]
@bartek-sarul Some of the ITK processing requirements, particularly for receiver requirements it is impossible to fulfill under current architecture ... particularly for Recipient – Patient Validation and Patient Transfer Specific Requirements

https://developer.nhs.uk/apis/itk3messagedistribution/explore_rec_req.html

**Comment by ejudgemeddbase** [comment]
**RETEST 1**
 
**TEST STEPS TO REPRODUCE ISSUE**
 
I re-ran request multi_pathology.edifact.dat and reviewed the FHIR output for the first response.

**ACTUAL RESULT**
 
[116Payload.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6746451/116Payload.txt)
![112](https://user-images.githubusercontent.com/82526722/124088405-d1f71c80-da4a-11eb-9764-978674a56f02.PNG)

I can clearly see a Message Header now appears.
 
**Retest 1 PASSED**
 
**Defect 112 Closed**
