### ISSUE TITLE
Specification Validation Error: Missing identifier system in the Diagnostic Report, and the identifier value is not UUID

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#113]
** Bugs ***
An identifier system is mandatory for Diagnostic Report FHIR resources, and the identifier value is not UUID.

![image](https://user-images.githubusercontent.com/2870531/113836760-16915580-9785-11eb-8837-561042583899.png)

and the further constraint on the diagnostic report in the NHS specification pages

![image](https://user-images.githubusercontent.com/2870531/113838250-7fc59880-9786-11eb-9639-4163183f121f.png)

**Step to reproduce**
1. Send a sample to the mailbox
2. Check the inbound queue on the adapter.
3. Check the DiagnosticReport->Identifier (there is no system element)

**Expected behavior**
There should be 'system' element to comply with the specification

**Comment by bartek-sarul** [comment]
EDIFACT has this as text. Need clarification from NHS

**Comment by bartek-sarul** [comment]
NHS suggestion is:
> ignore the STU3 guidance and put the EDIFACT identifier in the value element & leave the system out
