### ISSUE TITLE
While passing incorrect workflowID in environment variable is transforming edifact into FHIR

### ISSUE THREAD

**Issue by sonalVarma** [nhsconnect/integration-adaptor-lab-results#114]
**Description**
When updating workflowID of pathology message PATH_MEDRPT_V3 in env.fake-mesh.sh , and sending an edifact for screening message , is transforming into FHIR

**Steps to reproduce**
1.  Update the workflow id for pathology message - export WORKFLOW_ID=PATH_MEDRPT_V3
2.  Send send_message.sh with -    ./mesh.sh send C88062GP001 "@./../src/intTest/resources/success_uat_data/NHS004/screening_full_acceptance_with_nhsack.edifact.dat"

**Actual result** 
![image](https://user-images.githubusercontent.com/75005842/113864066-136b8900-97c8-11eb-9203-57f1202aefa3.png)
Message_id is generated . While checking in azure service bus , message is available in gp_outbound_queue and edifact is transformed to corresponding FHIR JSON as well.
Attached FHIR JSON -
 
[FHIR.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6271461/FHIR.txt)
![image](https://user-images.githubusercontent.com/75005842/113865407-ac4ed400-97c9-11eb-999e-e0343e28d1d4.png)

**Expected result**
Error should be displayed when incorrect workflow ID is passed.

@michael-kainos @bartek-sarul

**Comment by bartek-sarul** [comment]
@sonalVarma  Workflow IDs are to tell app and script from where to download / upload messages. At this moment there is no check to verify that interchange from a given workflow contains only matching messages.
Is this something that breaks the ability to use the adaptor?

**Comment by sonalVarma** [comment]
@bartek-sarul the functionality of the adaptor didn't break with this. Just wanted to confirm about the verification of workflowID with that of messages.

**Comment by bartek-sarul** [comment]
@sonalVarma we've decided not to treat workflows as indicators of interchange content but only the source and target of data. Most important are the message indicators of each interchange message header. This way a single interchange can have 002, 003 and 004 at the same time which does not break any specification.
