### ISSUE TITLE
Specification Validation Error: Procedure request code requires snomed coding

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#115]
**Bugs**
The procedure request code apparently requires some coding as below. At the moment, it is populated as 'unknown' text only (instead of SNOMED coding)

![image](https://user-images.githubusercontent.com/2870531/114036829-4f5e2700-9878-11eb-93de-d58fda4f9e4b.png)

** Step to reproduce **
1. Send a message with test request summary to  mailbox
2. Check the adapter inbound queue
3. Check the Procedure request resource, the code always 'unknown'

** Expected behavior **
Some Snomed coding for the code.

**Comment by bartek-sarul** [comment]
@Kusnaditjung can you attach the EDIFACT you used?

**Comment by Kusnaditjung** [comment]
think most (if not all of them) from the test sample in the repo.. .here one example


[full_acceptance_without_nhsack.edifact.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6284299/full_acceptance_without_nhsack.edifact.txt)

**Comment by bartek-sarul** [comment]
Need help from NHS

**Comment by bartek-sarul** [comment]
Following NHS guidance - a hardcoded value will be used
```
15220000 | Laboratory test (procedure)
```

**Comment by ejudgemeddbase** [comment]
**RETEST 1**
 
**TEST STEPS TO REPRODUCE ISSUE**
 
I re-ran request full_acceptance_without_nhsack.edifact.txt

**ACTUAL RESULT**
 
[115.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6742091/115.txt)
![115](https://user-images.githubusercontent.com/82526722/123988137-aa0ea700-d9bf-11eb-8df4-08ba27014975.png)

I checked the ProcedureRequest Resource and see the following:

 
**Retest 1 PASSED**
 
**Defect 115 Closed**
