### ISSUE TITLE
Specification Validation Error: Procedure request requester missing onbehalf element, and agent can be assigned to Organization

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#116]
**Bugs**
The procedure request requester element `contains` two elements ('agent' and 'onBehalfOf'), 'agent' should be populated with Practitioner reference, while 'onBehalfOf' should be populated with Organization).
At the moment the 'agent' element can be populated with either Practitioner or Organization (check multi_pathology_msg1.fhir.json in the repo)

![image](https://user-images.githubusercontent.com/2870531/114577516-f75a6280-9c73-11eb-9ef8-8032e6a7fee6.png)

** Step to reproduce**
1. Check the  multi_pathology_msg1.fhir.json
2. check Procedure request requester elements
3. check agent element       
      * agent can reference to Organization instead of Practitioner

**Expected Behaviour**
* agent element should refer to Practitioner resource

**Comment by bartek-sarul** [comment]
Will be done together with https://github.com/nhsconnect/integration-adaptor-lab-results/issues/112

**Comment by ejudgemeddbase** [comment]
**RETEST 1**
 
**TEST STEPS TO REPRODUCE ISSUE**
 
I re-ran request multi_pathology.edifact.dat and reviewed the FHIR output.

**ACTUAL RESULT**
 
[116Payload.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6746488/116Payload.txt)
 
![116](https://user-images.githubusercontent.com/82526722/124090130-7463cf80-da4c-11eb-8603-3bae0a84e793.png)
![116c](https://user-images.githubusercontent.com/82526722/124090273-978e7f00-da4c-11eb-8edc-132c9eca2311.png)

The agent and onBehalfOf elements have entries corresponding to the Practitioner and Organisation elements, respectively.

**Retest 1 PASSED**
 
**Defect 116 Closed**
