### ISSUE TITLE
Specification Validation Error: Patient Resources's name element missing mandatory  'use' element, and official name is mandatory

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#117]
**Bugs**
Patient resource 'name' element missing mandatory 'use' element, AND official name is mandatory.

![image](https://user-images.githubusercontent.com/2870531/114205897-b18b5a80-9952-11eb-83bf-152d643354e1.png)

** Step to reproduce**
1. check sample 'multi_pathology_msg1.fhir.json'
2. Check the occurrence of the missing element on the patient's name element

**Expected behaviors**
the use element is present per specification, and if there is sample data without  name this should be flagged as bad data ??

**Comment by ejudgemeddbase** [comment]
**RETEST 1**
 
**TEST STEPS TO REPRODUCE ISSUE**
 
I re-ran request multi_pathology.edifact.dat and reviewed the FHIR output for the first response.

**ACTUAL RESULT**
 
[116Payload.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6746742/116Payload.txt)
![117](https://user-images.githubusercontent.com/82526722/124094269-88113500-da50-11eb-82af-5864ff029c64.PNG)

I can see that the 'use' element now appears.
 
**Retest 1 PASSED**
 
**Defect 117 Closed**
