### ISSUE TITLE
Specification Validation Error: patient's nhs number identifier missing nhsNumberVerificationStatus extension

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#118]
**Bugs**

When patient's nhs number identifier present in the Patient resource, it is missing the nhsNumberVerificationStatus extension.

![image](https://user-images.githubusercontent.com/2870531/114207139-f5cb2a80-9953-11eb-9a72-bf6ecaaccabc.png)

**Step to reproduce**
1. Check sample data ''full_acceptance_without_nhsack.1.fhir.json'
2. check patient resource on nhs number identifier, it is missing nhsNumberVerificationStatus extension

** Expected behaviours**
the nhsNumberVerificationStatus present when patient nhs number identifier present

**Comment by bartek-sarul** [comment]
The verification status extension must have a value from 
https://fhir.hl7.org.uk/STU3/CodeSystem/CareConnect-NHSNumberVerificationStatus-1

Which value to choose?
Is this ok?
```
"code": "01",
"display": "Number present and verified"
```

**Comment by ejudgemeddbase** [comment]
That's great. Thanks.

**Comment by ejudgemeddbase** [comment]
**RETEST 1**
 
**TEST STEPS TO REPRODUCE ISSUE**
[full_acceptance_without_nhsack.edifact.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6746855/full_acceptance_without_nhsack.edifact.txt)

I re-ran request full_acceptance_without_nhsack and inspected the FHIR payload.

**ACTUAL RESULT**
 
[118bResponse.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6746871/118bResponse.txt)
![118b](https://user-images.githubusercontent.com/82526722/124096921-f6ef8d80-da52-11eb-9892-412a0e1a5330.PNG)

I see in the response that the nhsNumberVerificationStatus extension is present in the Patient Identifier.
 
**Retest 1 PASSED**
 
**Defect 118 Closed**
