### ISSUE TITLE
Specification Validation Error: Missing specimen mandatory identifier 

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#119]
**Bugs**
An identifier with system="https://tools.ieftf.org/html/rfc4122" in Specimen resource is a mandatory field, and must have an UUID value. This identifier is missing from the FHIR output

![image](https://user-images.githubusercontent.com/2870531/114414796-1212d580-9ba7-11eb-909f-dea684fd12cb.png)

**Step to reproduce**
Check 'full_acceptance_ithout_nhsack.1.fhir' for an example

**Expected behavior**
The identifier should be present in the FHIR output

**Comment by bartek-sarul** [comment]
Need NHS help

**Comment by bartek-sarul** [comment]
NHS suggestion:
> if the identifier is not available, just don’t populate the identifier
