### ISSUE TITLE
Specification Validation Error: Missing snomed code in Specimen type element

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#120]
**Bugs**
In specimen resource, when SNOMED code presents, the system, code and display elements are mandatory. The code element is missing at the moment

![image](https://user-images.githubusercontent.com/2870531/114420218-0a096480-9bac-11eb-9ba9-4d41ddd075f8.png)

**Step to reproduce**
Check 'full_acceptance_without_nhsack.1.fhir' for an example

**Expected behavior**
the snomed code should be present

**Comment by bartek-sarul** [comment]
Laboratory might not give us any code for this - only free text.
More to that, this requires SNOMED where Pathology gives us Read2

**Comment by ejudgemeddbase** [comment]
**RETEST 1**
 
**TEST STEPS TO REPRODUCE ISSUE**
 
[Pathology2.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6747990/Pathology2.txt)

I re-ran request pathology_2.edifact and inspected the FHIR load 
	
**ACTUAL RESULT**
 
[Pathology2FHIR.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6747993/Pathology2FHIR.txt)
![121Path2](https://user-images.githubusercontent.com/82526722/124123665-7723ec00-da6f-11eb-9260-4a13112cdd56.PNG)

I see that the Code now appears in the Specimen Resource, but no System - as mentioned in an earlier comment.

**Retest 1 PASSED**

**Issue 120 CLOSED**
