### ISSUE TITLE
Specification Validation Error: The ProcedureRequest status must have a value of 'active'

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#121]
** Bugs **
ProcedureRequest status must be always 'active'. At the moment this is set to 'unknown'

![image](https://user-images.githubusercontent.com/2870531/114551411-421bb080-9c5b-11eb-84fc-eaebff584016.png)

** Step to reproduce **
1. check 'multi_pathology_msg1.fhir.json'
2. Check ProcedureRequest status element value, which is 'unknown'. This should be always 'active';

** Expected behavior**
ProcedureRequest status value must be always 'active' as per specification.

**Comment by ejudgemeddbase** [comment]
**RETEST 1**
 
**TEST STEPS TO REPRODUCE ISSUE**
 
I re-ran request multi_pathology_msg and inspected the FHIR payload.

**ACTUAL RESULT**
 
[multi_pathology_1_payload.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6747445/multi_pathology_1_payload.txt)
![121](https://user-images.githubusercontent.com/82526722/124107610-518de700-da5d-11eb-972a-4b1116af5170.PNG)

The ProcedureStatus value is 'active'.
 
**Retest 1 PASSED**
 
Defect 121 Closed
