### ISSUE TITLE
Spesification Validation Error: Practitioner SDSUserId is populated with value which is not SDSUserId

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#122]
**Bugs **
Practitioner SDSUserId is populated with value which is not SDSUserId
![image](https://user-images.githubusercontent.com/2870531/114582537-94b79580-9c78-11eb-933c-c02acdfa900b.png)

** Step to reproduce **
* check 'multi_pathology_msg1.fhir.json'
* Check practitioner identifier with system 'https://fhir.nhs.uk/Id/sds-user-id'
* check that the identifier value is not an SDSUserId (seems something else, probably GMC code ??)

** Expected behavior **
The value should reflect the 'system' value, otherwise, it will be misleading.

**Comment by bartek-sarul** [comment]
We have no SDS User ID information in EDIFACT

**Comment by bartek-sarul** [comment]
NHS suggestion:
> as we don’t know which system the identifier comes from, just leave the system out

**Comment by ejudgemeddbase** [comment]
**RETEST 1**
 
**TEST STEPS TO REPRODUCE ISSUE**
 
I re-ran request multi_pathology_msg and inspected the FHIR payload.

**ACTUAL RESULT**
 
[multi_pathology_1_payload.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6747448/multi_pathology_1_payload.txt)
![122](https://user-images.githubusercontent.com/82526722/124108229-f01a4800-da5d-11eb-9a95-96d1e012280d.PNG)

The System value no longer appears for Practitioner resource.
 
**Retest 1 PASSED**
 
Defect 122 Closed
