### ISSUE TITLE
No laboratory investigation result type for ""

### ISSUE THREAD

**Issue by ejudgemeddbase** [nhsconnect/integration-adaptor-lab-results#123]
**Bugs**
The error _No laboratory investigation result type for ""_ appears when the following request is run:

UNA:+.? 'UNB+UNOC:3+000000004400001:80+000000024600002:80+100301:1751+1015++MEDRPT++1'UNH+1+MEDRPT:0:1:RT:NHS003'BGM+LSR'DTM+137:200302211150:203'S01+01'NAD+MR+G3313909:900++Dr Ansell'SPR+PRO'S01+01'NAD+MR+J82150:901'SPR+ORG'S01+01'NAD+PO+G3313909:900++Dr Ansell'SPR+PRO'S01+01'NAD+SLA+++SALISBURY HEALTH CARE NHS TRUST'SPR+ORG'S01+01'NAD+SLA+++Laboratory Medicine'SPR+DPT'S02+02'GIS+N'RFF+SRI:CHM0100950302121100G,03.0999008001'STS++UN'DTM+ISR:200302211150:203'S06+06'S07+07'PNA+PAT+9999999530:OPI+++SU:TEST8+FO:EMIS8'DTM+329:19720312:102'PDI+1'S16+16'SEQ++1'SPC+TSP+:::Blood'RFF+STI:G,03.0999008.K'DTM+SCO:20030109:102'DTM+SRI:200301091354:203'GIS+N'INV+MQ+44V..:911::Glucose tolerance test'SEQ++1'FTX+SPC+++NB NEW WHO/DIABETES UK CLASSIFICATION CRITERIA FROM 01.06.00:Dr. N.O?'Connell'RFF+ASL:1'GIS+N'INV+MQ+:::FT1'RSL+++++PA'FTX+RIT+++           Oral dose?: 75g anhydrous glucose given as:                     113ml Polycal liquid:          Plasma Glucose           Urine Results: Time        (mmol/l)         Ketones         Glucose'RFF+ARL:1'GIS+N'INV+MQ+:::FT2'RSL+++++PA'FTX+RIT+++ Fasting       4.3            negative        negative: 2 hours       7.6            negative        negative: NORMAL              ?: Fasting up to 6.0 & 2 hr up to 7.7: IMPAIRED FASTING    ?: Fasting 6.1-6.9 & 2 hr up to 7.7'RFF+ARL:1'GIS+N'INV+MQ+:::FTX3'RSL+++++PA'FTX+RIT+++     GLYCAEMIA: IMPAIRED GLUCOSE    ?: Fasting up to 6.9 & 2 hr 7.8-11.0:     TOLERANCE: *DIABETES MELLITUS  ?: Fasting 7.0 or above &/or'RFF+ARL:1'GIS+N'INV+MQ+:::FTX4'RSL+++++PA'FTX+RIT+++                                      2 hr 11.1 or above: *(must also have symptoms - polyuria, polydipsia,:   unexplained weight loss)'RFF+ARL:1'UNT+60+1'UNZ+1+1015'

**Steps to Reproduce**
See the above.

**Expected Behaviour**
To be determined. It's possible that this request is bad (i.e. has an invalid parameter), but it is one we received from Edge (mutliTextResultEdi.dat), so thought to check.

**Comment by bartek-sarul** [comment]
@ejudgemeddbase can you explain what does the `RSL+++++PA'` meaning is?
![image](https://user-images.githubusercontent.com/10883492/117149153-3d0fd400-adb7-11eb-89b2-85436bbdd384.png)
Does this mean that your RSL does not hold any numeric value but just the PA (Potentialy Abnormal) indicator? Is this value?

**Comment by ejudgemeddbase** [comment]
@Kusnaditjung Do you have any thoughts?

**Comment by Kusnaditjung** [comment]
HI @bartek-sarul  and @ejudgemeddbase  I am not an expert on EDIFACT, but looking from the spec here  

Looking from the spec in the 'Spec_03_A_010.doc '

![image](https://user-images.githubusercontent.com/2870531/117167805-7e0be680-adbf-11eb-9b03-97c818fae923.png)

PA is Result Normalcy which has a value set
![image](https://user-images.githubusercontent.com/2870531/117168161-d347f800-adbf-11eb-9f09-7be0fbf7f1b1.png)

I tend to interpret that this is not conforming with the standard document, but there is a possibility the value set has been extended beyond the standard documentation (I am not sure if EDIFACT supports extension Valueset like in FHIR or not). I would tend to   filter this out as non conforming message, or accept this by adding additional value set (PA) to the result normalcy indicator

**Comment by bartek-sarul** [comment]
@Kusnaditjung my question is more about RSL not having "result type" at all but only the "result normacy indicator". The missing "result type" is causing the issue here, not the "PA".
But it is interesting that in your second screenshots values are different than what is in the other LSR document

**Comment by Kusnaditjung** [comment]
@bartek-sarul  from the spec "Spec_03_A_010.doc". Does it seem the result type should be conditional, not mandatory ??

**Comment by bartek-sarul** [comment]
Following NHS suggestions:
```
This would go in Observation.interpretation & use the CodeableConcept.code to hold the code and CodeableConcept.display to hold the text (no system)
```

**Comment by michael-kainos** [comment]
This is for the RSL+++++PA edifact segment 

RSL may provide coded value - in this case it will be stored in CodeableConcept.code and display.
The one from Edge (mutliTextResultEdi.dat) example doesn't have code but only PA indicator which is translated into Potentially Abnormal and is stored in Observation.interpretation

**Comment by ejudgemeddbase** [comment]
**RETEST 1**
 
**TEST STEPS TO REPRODUCE ISSUE**
 
Re-ran request mutliTextResultEdi.dat to the Pathology adaptor.

**ACTUAL RESULT**
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/82526722/123941599-37d39d80-d992-11eb-85d7-d59c4cd700b2.png)
[123FhirPayload.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6739932/123FhirPayload.txt)

 
A response appeared in the application. No error appeared in the logs either (which is where the original error was found).
 
**Retest 1 PASSED**
 
**Defect 123 Closed**
