### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 2

### ISSUE THREAD

**Issue by ejudgemeddbase** [nhsconnect/integration-adaptor-lab-results#125]
The following Pathology_IRA request produces the above error:

`UNA:+.? '
UNB+UNOC:3+000000004400001:80+000000024600002:80+100301:1751+1015++MEDRPT++1'
UNH+1+MEDRPT:0:1:RT:NHS003'
BGM+LSR'
DTM+137:201002261541:203'
S01+01'
NAD+PO'
SPR+PRO'
S01+01'
NAD+MR+G3380314:900++SCOTT'
SPR+PRO'
S01+01'
NAD+MR+D82015:901'
SPR+ORG'
S01+01'
NAD+SLA+++Haematology'
SPR+DPT'
S01+01'
NAD+SLA+++ST JAMES?'S UNIVERSITY HOSPITAL'
SPR+ORG'
S02+02'
GIS+N'
RFF+SRI:15/CH000037K/200010191704'
STS++UN'
DTM+ISR:201002251541:203'
S06+06'
ADR++US:FLAT1:59 SANDTOFT ROAD:BELTON:DONCASTER:++DN9 1PJ'
S07+07'
PNA+PAT+9435492908:OPI+++SU:AZIZ+FO:NISMA'
DTM+329:19450730:102'
PDI+2'
S10+10'
CIN+UN'
FTX+CID+++TIRED ALL THE TIME, LOW Hb'
S16+16'
SEQ++1'
SPC+TSP+:::VENOUS BLOOD'
RFF+STI:CH000037KA'
DTM+SCO:201002231541:203'
DTM+SRI:201002241541:203'
GIS+N'
INV+MQ+42R4.:911::Serum ferritin'
RSL+NV+11++:::ng/mL'
RFF+ASL:1'
S20+20'
RND+U+10+200'
FTX+RPD+++Upper age - 45 years:Sex - Female'
UNT+46+1'
UNZ+1+1015'
`

**Comment by bartek-sarul** [comment]
@ejudgemeddbase you have `NAD+PO'` which I think is invalid and should have some values:
![Uploading image.png…]()

**Comment by ejudgemeddbase** [comment]
Thanks.
