### ISSUE TITLE
Message header-trailer count mismatch: 1-2

### ISSUE THREAD

**Issue by ejudgemeddbase** [nhsconnect/integration-adaptor-lab-results#126]
The following request yields the above error:

UNA:+.? '
UNB+UNOC:3+000000073300001:80+000000147500001:80+001023:1731+109++MEDRPT++1++1'
        &LGIM0501.INT        UNH+1+MEDRPT:0:1:RT:NHS003'
BGM+LSR'
DTM+137:200010221705:203'
S01+01'
NAD+PO+G1234545:900++ROLT R'
SPR+PRO'
S01+01'
NAD+MR+G1234545:900++ROLT R'
SPR+PRO'
S01+01'
NAD+MR+B86123:901'
SPR+ORG'
S01+01'
NAD+SLA+++CHEMICAL PATHOLOGY'
SPR+DPT'
S01+01'
NAD+SLA+++ST JAMES?'
S UNIVERSITY HOSPITAL'
SPR+ORG'
S02+02'
GIS+N'
RFF+SRI:109/CH1050101A/200010211704'
STS++UN'
DTM+ISR:200010211704:203'
S06+06'
S07+07'
PNA+PAT+6438772941:OPI+++SU:WOOD+FO:SHAUN'
DTM+329:19950127:102'
PDI+1'
S10+10'
CIN+UN'
FTX+CID+++High Blood Sugar.'
S16+16'
SEQ++1'
SPC+TSP+:::BLOOD'
RFF+STI:CH1050101A'
DTM+SCO:200010191030:203'
DTM+SRI:200010201542:203'
GIS+N'
INV+MQ+44g..:911::Plasma glucose level'
RSL+NV+4.8++:::mmol/L'
RFF+ASL:1'
S20+20'
RND+U+3.0+5.5'
UNT+44+1'
UNH+2+MEDRPT:0:1:RT:NHS003'
BGM+LSR'
DTM+137:200010221705:203'
S01+01'
NAD+PO+G1234545:900++ROLT R'
SPR+PRO'
S01+01'
NAD+MR+G1234545:900++ROLT R'
SPR+PRO'
S01+01'
NAD+MR+B86123:901'
SPR+ORG'
S01+01'
NAD+SLA+++CHEMICAL PATHOLOGY'
SPR+DPT'
S01+01'
NAD+SLA+++ST JAMES?'
S UNIVERSITY HOSPITAL'
SPR+ORG'
S02+02'
GIS+N'
RFF+SRI:109/CH1050102B/200010211704'
STS++UN'
DTM+ISR:200010211704:203'
S06+06'
S07+07'
PNA+PAT++++SU:THOMPSON+FO:STEPHANIE'
DTM+329:19590122:102'
PDI+2'
S16+16'
SEQ++1'
SPC+TSP+:::Serum'
RFF+STI:CH1050102B'
DTM+SCO:200010191000:203'
DTM+SRI:200010201248:203'
GIS+N'
INV+MQ+:::Gonadotrophin levels'
SEQ++1'
FTX+SPC+++Reference ranges   Follicular     Luteal     Post-menopausal:F.S.H.             1.0 -  9.0   1.0 - 9.0         > 30.0:Oestradiol         110 - 180    550 - 850         < 100'
RFF+ASL:1'
GIS+N'
INV+MQ+443h.:911::Serum FSH level'
RSL+NV+30:6++:::iu/L'
RFF+ARL:1'
GIS+N'
INV+MQ+4465.:911::Serum oestradiol level'
RSL+NV+204++:::pmol/L'
RFF+ARL:1'
UNT+48+2'
UNZ+2+109'

**Comment by bartek-sarul** [comment]
Error message seems correct
This:
```
UNA:+.? '
UNB+UNOC:3+000000073300001:80+000000147500001:80+001023:1731+109++MEDRPT++1++1'
&LGIM0501.INT UNH+1+MEDRPT:0:1:RT:NHS003'
BGM+LSR'
```
doesn't look like a valid EDIFACT:
1) UNB has additional `++1` but this actually shouldn't break anything
2) Text: `&LGIM0501.INT ` is before `UNH` making it unparseable which eventually lead to the error you see. Parser sees 1 UNH and 2 UNT segments

**Comment by ejudgemeddbase** [comment]
Thanks.
