### ISSUE TITLE
No test status code for 'FR'

### ISSUE THREAD

**Issue by ejudgemeddbase** [nhsconnect/integration-adaptor-lab-results#127]
The following request produces the above error:

`UNA:+.? 'UNB+UNOB:2+000000073300001:80+000000147500001:80+010530:1517+137++MEDRPT'UNH+1+MEDRPT:0:1:RT:NHS002'BGM+LSR'DTM+137:200103301723:203'S01+01'NAD+PO+G1234538:900++Sangeeta Singh'SPR+PRO'S01+01'NAD+PO+B86123:901'SPR+ORG'S01+01'NAD+SLA+++Haematology Dept.'SPR+DPT'S01+01'NAD+SLA+RQR00:903'SPR+ORG'S02+02'GIS+N'RFF+SRI:1015/HA2302101W/200103301623'STS++UN'DTM+ISR:200103301623:203'FTX+SPC+++Copy of report.:Investigations requested by Dr Curley, Cardiology Department.'S06+06'RFF+SSI:Z77553311'ADR++US:CLIFF DENE:CLIFF ROAD:LEEDS++LS6 2NR'S07+07'PNA+PAT+9619750977:OPI+US++SU:JOHNSON+FO:AMBER'DTM+329:19240418:102'S07+07'PNA+PER++MA++AL:AMBER SMITH'S10+10'CIN+UN'FTX+CID+++ON AZATHIOPRINE'S16+16'SEQ++1'SPC+TSP+T002:920'RFF+STI:HA2302101W'DTM+SCO:20010330:102'GIS+N'INV+MQ+424..:911'SEQ++1'STS++FR'RFF+ASL:1'GIS+N'INV+MQ+42H..:911'RSL+NV+7.6:4++10*9/L:923+NM'RFF+ARL:1'S20+20'RND+R+4.0+11.0'GIS+N'INV+MQ+426..:911'RSL+NV+2.84:4++10*12/L:923+SL'RFF+ARL:1'S20+20'RND+R+3.8+5.4'GIS+N'INV+MQ+423..:911'RSL+NV+11.0:4++g/dL:923+NM'RFF+ARL:1'S20+20'RND+R+10.5+15.0'GIS+N'INV+MQ+425..:911'RSL+NV+0.315:4++%:923+LO'RFF+ARL:1'S20+20'RND+R+0.370+0.470'GIS+N'INV+MQ+42A..:911'RSL+NV+111.1:4++fL:923+SH'RFF+ARL:1'S20+20'RND+R+76+100'GIS+N'INV+MQ+428..:911'RSL+NV+38.7:4++pg:923+HI'RFF+ARL:1'S20+20'RND+R+26+32'GIS+N'INV+MQ+429..:911'RSL+NV+34.8:4++g/dL:923+NM'RFF+ARL:1'S20+20'RND+R+30+37'GIS+N'INV+MQ+42P..:911'RSL+NV+220:4++10*9/L:923+NM'RFF+ARL:1'S20+20'RND+R+150+600'GIS+N'INV+MQ+42J..:911'RSL+NV+7.4:4++10*9/L:923+NM'RFF+ARL:1'S20+20'RND+R+2.0+7.5'GIS+N'INV+MQ+42M..:911'RSL+NV+1.1:4++10*9/L:923+NM'RFF+ARL:1'S20+20'RND+R+1.0+4.0'GIS+N'INV+MQ+42N..:911'RSL+NV+0.4:4++10*9/L:923+NM'RFF+ARL:1'S20+20'RND+R+0.2+1.0'GIS+N'INV+MQ+42K..:911'RSL+NV+0.1:7++10*9/L:923+NM'RFF+ARL:1'S20+20'RND+R+0+0.6'GIS+N'INV+MQ+42L..:911'RSL+NV+0.0:4++10*9/L:923+NM'RFF+ARL:1'S20+20'RND+R+0.00+0.3'GIS+N'INV+MQ+43A..:911'RSL+++++UN'STS++FR'FTX+RIT+++POSITIVE'RFF+ASL:1'GIS+N'INV+MQ+42B..:911'STS++NA'RFF+ASL:1'UNT+131+1'UNH+2+MEDRPT:0:1:RT:NHS002'BGM+LSR'DTM+137:200103301723:203'S01+01'NAD+PO+G1234521:900++Tristan Trotter'SPR+PRO'S01+01'NAD+PO+B86123:901'SPR+ORG'S01+01'NAD+SLA+++P PRESLAND'RFF+AHI:PREPX'SPR+PRO'S01+01'NAD+SLA+++Microbiology'SPR+DPT'S01+01'NAD+SLA+RQR00:903'SPR+ORG'S02+02'GIS+N'RFF+SRI:1015/MI2302102X/200103301623'STS++UN'DTM+ISR:200103301623:203'S06+06'S07+07'PNA+PAT+ABRF954:OPI+++SU:WOODHOUSE+FO:ALISTAIR'DTM+329:19110212:102'PDI+1'S16+16'SEQ++1'SPC+TSP+T008:920'PRC+SCO+:::ASPIRATION'RFF+STI:MI2302102X'QTY+SVO:10+mL'DTM+SRI:200103301223:203'FTX+ALD+++LEFT KNEE'GIS+N'INV+MQ+4I16.:911'SEQ++1'STS++FR'DTM+AIP:200103301523:203'FTX+SPC+++No growth obtained.'RFF+ASL:1'GIS+N'INV+MQ+4I15.:911'STS++FR'FTX+RIT+++Polys ?+?+?+'RFF+ARL:1'GIS+N'INV+MQ+:::Gram'STS++FR'FTX+RIT+++No organisms seen'RFF+ARL:1'GIS+N'INV+MQ+:::Z.N.'STS++FR'FTX+RIT+++No A.A.F.B. seen'RFF+ARL:1'GIS+N'INV+MQ+4J17.:911'STS++FR'FTX+RIT+++T.B. Culture Mycobacterium sp NOT isolated after 6 weeks incubation.'RFF+ARL:1'UNT+65+2'UNH+3+MEDRPT:0:1:RT:NHS002'BGM+LSR'DTM+137:200103301723:203'S01+01'NAD+PO+G1234521:900++Tristan Trotter'SPR+PRO'S01+01'NAD+PO+B86123:901'SPR+ORG'S01+01'NAD+SLA+++Haematology'SPR+DPT'S01+01'NAD+SLA+RQR00:903'SPR+ORG'S02+02'GIS+N'RFF+SRI:1015/HA2302103Y/200103301623'STS++UN'DTM+ISR:200103301623:203'S06+06'ADR++US:1 WEST DENE:LEEDS++LS17 8QT'S07+07'PNA+PAT+5681121828:OPI+US++SU:POTTER+FO:KERRY+MI:B+TI:MRS.'DTM+329:19690819:102'PDI+2'S10+10'CIN+UN'FTX+CID+++TIRED ALL THE TIME, LOW Hb'FTX+CID+++TIRED ALL THE TIME, LOW Hb'S16+16'SEQ++1'SPC+TSP+T002:920'RFF+STI:HA2302103Y'DTM+SCO:200103300923:203'DTM+SRI:200103301223:203'GIS+N'INV+MQ+42R4.:911'RSL+NV+11:4++ng/mL:923+NM'DTM+AIP:200103301523:203'RFF+ASL:1'S20+20'RND+U+10+200'FTX+RPD+++Upper age - 45 years:Sex - Female'UNT+45+3'UNZ+3+137'`

**Comment by bartek-sarul** [comment]
@ejudgemeddbase this is a similar case as https://github.com/nhsconnect/integration-adaptor-lab-results/issues/130 where indeed `SR` was not mapped correctly but for this one I don't see `FR` being an supported code.
I'm looking at `LSR_03_B_003.doc` and it says only 2 codes are allowed
```
E139 | status   of laboratory investigation (result item)
-- | --
PR | Preliminary   (Interim) result
SR | Supplementary result
```

**Comment by ejudgemeddbase** [comment]
@bartek-sarul Thanks for looking into this Just to confirm: is this just an invalid request then and the issue can be closed?

**Comment by bartek-sarul** [comment]
looks like an invalid request for wich an NHSACK should be generated

**Comment by bartek-sarul** [comment]
@ejudgemeddbase please close the ticket if you are happy with my answer
