### ISSUE TITLE
UNB: Attribute sequenceNumber must be between 1 and 99999999

### ISSUE THREAD

**Issue by ejudgemeddbase** [nhsconnect/integration-adaptor-lab-results#128]
The above error is caused by the attached request
[5910_663_Messages_1.zip](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6336233/5910_663_Messages_1.zip)

**Comment by bartek-sarul** [comment]
@ejudgemeddbase following segment
`UNB+UNOC:3+110000381000005:80+500023147100005:80+110216:0934+1000000001++MEDRPT++1'`
has interchange sequence number set to `1000000001`
Based on our previous experience in another EDIFACT based project (NHAIS), this value must be between 1 and 99999999

**Comment by ejudgemeddbase** [comment]
Thanks.
