### ISSUE TITLE
Specification Validation Error: Test Result (observation) interpretation missing binding to 'https://fhir.hl7.org.uk/STU3/ValueSet/CareConnect-ExtendedInterpretationCode-1'

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#131]
**Bugs**
The Observation interpretation value is bound to "http://hl7.org/fhir/ValueSet/observation-interpretation" or 'https://fhir.hl7.org.uk/STU3/ValueSet/CareConnect-ExtendedInterpretationCode-1' value set (the last one does not exist, so the first one should take precedence ??) 

![image](https://user-images.githubusercontent.com/2870531/115246977-472aa500-a11e-11eb-99c2-e52e35afa16c.png)

![image](https://user-images.githubusercontent.com/2870531/115248150-59f1a980-a11f-11eb-9039-816fbf92494d.png)

**Step to reproduce**
1. Check test result with interpretation (for example 'NHS003' full_acceptance_with_nhsack.2.fhir.json)
2. Check that the interpretation missing the expected binding,  

**Expected behaviour**
Binding to "http://hl7.org/fhir/ValueSet/observation-interpretation" or 'https://fhir.hl7.org.uk/STU3/ValueSet/CareConnect-ExtendedInterpretationCode-1' are expected

**Comment by ejudgemeddbase** [comment]
**RETEST 1**
 
**TEST STEPS TO REPRODUCE ISSUE**
 
[full_acceptance_with_nhask_edifact.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6747603/full_acceptance_with_nhask_edifact.txt)

I re-ran request full_acceptance_with_nhsack and inspected the FHIR load 
	
**ACTUAL RESULT**
 
[full_acceptance_2.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6747605/full_acceptance_2.txt)
![131](https://user-images.githubusercontent.com/82526722/124113441-5a81b700-da63-11eb-9070-89c5bd18c241.PNG)

I see the Observation Interpretation bindings are as expected.

**Retest 1 PASSED**

**Issue 131 CLOSED**
