### ISSUE TITLE
Specification Validation Error: Missing Accession identifier on Specimen Resource

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#133]
**Bugs**
Missing Accession identifier on Speciment resource. 
![image](https://user-images.githubusercontent.com/2870531/115253661-7f34e680-a124-11eb-9c4b-621914ddcbca.png)

**Step to reproduce**
Check on :
* multi_pathology_ms2.fhir.json
* screening.fhir.json
* All screening message 

**Expected behaviors**
Accession number or other screening identifier (if accession does not exist ??) must be populated.

**Comment by bartek-sarul** [comment]
Need NHS help as we don't see any form of business identification in EDIFACT

**Comment by bartek-sarul** [comment]
This value comes from `SG16.RFF.C506.1154`
If it's not in EDIFACT then there won't be any identifier

**Comment by bartek-sarul** [comment]
As a fix I'll remove the `acme.org` identifier as surely it's an incorrect one
