### ISSUE TITLE
Specificaiton Validation Error: Observation resource missing IEFT identifier which should be an UUID or GUId

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#134]
**Bugs**
Observation resource missing mandatory IETF identifier which should've an UUID or GUID value 
![image](https://user-images.githubusercontent.com/2870531/115255055-d1c2d280-a125-11eb-8414-34637248078f.png)

**Step to reproduce**
Most of the INT sample message

**Expected behaviors**
The observation has identifier which system is 'https://tools.ietf.org/html/rfc4122' and a value of UUID or GUID

**Comment by bartek-sarul** [comment]
Need NHS help as we don't have anything in EDIFACT for this

**Comment by bartek-sarul** [comment]
NHS suggestion:
>  if you have an identifier, put it in value, if you don’t have one miss out the element

We don't have anything to map from so there won't be any identifier here
