### ISSUE TITLE
Specification Validation Error: MIssing Test result Observation 'related''s type(with value derived-from).

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#135]
**Bugs**
Missing test result in observation 'related''s type (derived-from).

![image](https://user-images.githubusercontent.com/2870531/115257715-439c1b80-a128-11eb-9f70-ae8782ed9356.png)

**Step to reproduce**
check:
* pathology_2.fhir.json
* pathology_3.fhir.json
* NHS002->full_acceptance_without_nhsack.1.fhir.json
* NHS003-> All messages

**Expected behaviour**
test result (Observation) related's type element must be populated if it refers to a test group.

**Comment by bartek-sarul** [comment]
Need NHS help

**Comment by michael-kainos** [comment]
Changed bi-directional reference between Observation and Specimen resources
 
Only Observation resources will contain reference to Specimen resources. There is now no Specimen resources which has a reference to Observation resources

**Comment by jhoey-med** [comment]
### RETEST 1
 
**TEST STEPS TO REPRODUCE ISSUE**

Check the FHIR payloads of each of the below messages after sending their corresponding EDIFACT messages to the adaptor

- pathology_2.fhir.json
- pathology_3.fhir.json
- NHS002->full_acceptance_without_nhsack.1.fhir.json

**ACTUAL RESULT**
 
Element 'type' is now present in each of the FHIR responses

Please see screenshots attached.

pathology3
![image](https://user-images.githubusercontent.com/81386191/124136901-19969c00-da7d-11eb-8944-34061564b951.png)

pathology2
![image](https://user-images.githubusercontent.com/81386191/124141130-0d144280-da81-11eb-9f67-36915e7b3564.png)

 
Retest 1 **PASSED**
 
Defect 135 Closed
