### ISSUE TITLE
Specification Validation Error: Invalid Test Result (Observation) value (

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#136]
**Bugs**
Test results (Observation) value element must have a value of Quantity instead of CodeableConcept, and the value must be populated either (but not both)
* as boolean in the Extension with url = "https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-ValueApproximation-1"
* value  (and possible unit) element
![image](https://user-images.githubusercontent.com/2870531/115260743-ee153e00-a12a-11eb-9446-84602997ac95.png)

**Step to reproduce**
Check: all screening messages

**Expected behavior**
The Observation Value must be a Quantity, with extension OR Quantity value

**Comment by bartek-sarul** [comment]
@Kusnaditjung for NHS004 messages a new RSL segment result code has been introduced - CV (coded value)
The RSL gives us then different type of information. Please check the https://gpitbjss.atlassian.net/wiki/spaces/GPITF/pages/1391133789/Screening+messaging and https://gpitbjss.atlassian.net/wiki/download/attachments/1391133789/Cancer%20Screening%20-%20eGP-Comms%20GP%20Software%20Supplier%20Requirements%20v4.1.doc?version=1&modificationDate=1520365800044&cacheVersion=1&api=v2 file

![image](https://user-images.githubusercontent.com/10883492/116400943-f0625100-a82a-11eb-8e0a-753b231e886c.png)

The Observation profile https://fhir.hl7.org.uk/STU3/StructureDefinition/CareConnect-Observation-1 allows using `valueCodeableConcept`

**Comment by Kusnaditjung** [comment]
HI @bartek-sarul I can be wrong,  my current understanding working previously with GPConnect specification which seems similar to pathology and screening is  CareConnect profile is built on the top of FHIR STU3 (or DSTU3), and on the top of that we have NHS pages specification which further constraint CareConnect profiles (this ideally should be made in profile or some modeling artifact, but at the moment they are just specified in the web pages so need to manually curate them, this is what we have done in GPConnect). I think the webpage clearly mentioning Quantity with extension (see below)

![image](https://user-images.githubusercontent.com/2870531/116404664-c575fe00-a826-11eb-94e8-dd9931dad6b6.png)

If we follow the spec, this may mean the codeable concept may need to translate to Quantity (and boolean extension).. which is not always possible (I think). Alternatively we can give a note in the adapter documentation about deviation from the specification, and draft our own implementation (e.g Value is "Quantity (extension) or Codeable concept" OR just "Codeable concept". That will be a call between Kainos and NHSD, I will follow what is the final decision (or you may other interpretation ??)

**Comment by bartek-sarul** [comment]
I'll confirm this with NHSD

**Comment by bartek-sarul** [comment]
NHS agrees with current approach - NHS004 can supply code instead of quantity, so the Observation.value can be valueCodeableConcept
