### ISSUE TITLE
Clarification: Condition resource in Procedure request reasonReference

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#137]
**Issues**
The procedure request has an element called 'reasonReference' which is a reference to 'Condition' resource, but not appear in any logical model, the cardinality is 'Required'. Can you clarify whether this element can be ignored or not for Pathology adapter work

**Comment by bartek-sarul** [comment]
NHS clarifies this as following:

```
Condition resource is not required within the context of EDIFACT NHS003 messages.  However free text relating to the test request such as “ON WARFARIN”, carried in EDIFACT SG10.FTX.C108.4440(1-5) (clinical observation description), should be mapped to FHIR ProcedureRequest.note. 
```

All free texts are already mapped to `ProcedureRequest.note` list
