### ISSUE TITLE
UNB: Attribute translationTime is required

### ISSUE THREAD

**Issue by ejudgemeddbase** [nhsconnect/integration-adaptor-lab-results#138]
The following request produces the above error:

UNA:+.? 'UNB+UNOC:3+000000073300001:80+000000147500001:80++1028++MEDRPT'UNH+1+MEDRPT:0:1:RT:NHS003'BGM+LSR'DTM+137:200103301736:203'S01+01'NAD+PO+G1234538:900++Sangeeta Singh'SPR+PRO'S01+01'NAD+MR+G1234538:900++Sangeeta Singh'SPR+PRO'S01+01'NAD+MR+B86123:901'SPR+ORG'S01+01'NAD+SLA+++Haematology'SPR+DPT'S01+01'NAD+SLA+++ST JAMES?'S UNIVERSITY HOSPITAL'SPR+ORG'S02+02'GIS+N'RFF+SRI:1028/HA6002201M/200103301636'STS++UN'DTM+ISR:200103301636:203'S06+06'ADR++US:118 SHEPHERDS LANE:LEEDS++LS7 4DZ'S07+07'PNA+PAT++++SU:HILSON+FO:AUDREY'DTM+329:19340123:102'PDI+2'S10+10'CIN+UN'FTX+CID+++TATT'S16+16'SEQ++1'SPC+TSP+:::VENOUS BLOOD'RFF+STI:HA6002201M'DTM+SCO:20010330:102'GIS+N'INV+MQ+424..:911::Full blood count - FBC'SEQ++1'RFF+ASL:1'GIS+N'INV+MQ+42H..:911::Total white cell count'RSL+NV+7.2++:::10*9/L'RFF+ARL:1'S20+20'RND+U+4.0+11.0'GIS+N'INV+MQ+426..:911::Red blood cell (RBC) count'RSL+NV+3.16++:::10*12/L'RFF+ARL:1'S20+20'RND+U+3.8+5.4'GIS+N'INV+MQ+423..:911::Haemoglobin estimation'RSL+NV+9.4++:::g/dL+LO'RFF+ARL:1'S20+20'RND+U+10.5+15.0'GIS+N'INV+MQ+4258.:911::Haematocrit'RSL+NV+0.371++:::%'RFF+ARL:1'S20+20'RND+U+0.370+0.470'GIS+N'INV+MQ+42A..:911::Mean corpuscular volume (MCV)'RSL+NV+84.1++:::fL'RFF+ARL:1'S20+20'RND+U+76+100'GIS+N'INV+MQ+428..:911::Mean corpusc. haemoglobin(MCH)'RSL+NV+30.6++:::pg'RFF+ARL:1'S20+20'RND+U+26+32'GIS+N'INV+MQ+429..:911::Mean corpusc. Hb. conc. (MCHC)'RSL+NV+34.2++:::g/dL'RFF+ARL:1'S20+20'RND+U+30+37'GIS+N'INV+MQ+42P..:911::Platelet count'RSL+NV+188++:::10*9/L'RFF+ARL:1'S20+20'RND+U+150+600'GIS+N'INV+MQ+42J..:911::Neutrophil count'RSL+NV+4.3++:::10*9/L'RFF+ARL:1'S20+20'RND+U+2.0+7.5'GIS+N'INV+MQ+42M..:911::Lymphocyte count'RSL+NV+1.2++:::10*9/L'RFF+ARL:1'S20+20'RND+U+1.0+4.0'GIS+N'INV+MQ+42N..:911::Monocyte count'RSL+NV+0.1++:::10*9/L'RFF+ARL:1'S20+20'RND+U+0.2+1.0'GIS+N'INV+MQ+42K..:911::Eosinophil count'RSL+NV+0.1++:::10*9/L'RFF+ARL:1'S20+20'RND+U+0+0.6'GIS+N'INV+MQ+42L..:911::Basophil count'RSL+NV+0.0++:::10*9/L'RFF+ARL:1'S20+20'RND+U+0.00+0.3'UNT+120+1'UNZ+1+1028'

**Comment by bartek-sarul** [comment]
According to documentation `DATE/TIME OF PREPARATION` is mandatory in `UNB`
![image](https://user-images.githubusercontent.com/10883492/117158667-eb1f7c00-adbf-11eb-8aad-391752788c39.png)
I understand that the error message might not be 100% clear about this but comparing presented `UNB` segment with documentation highlights this

**Comment by ejudgemeddbase** [comment]
Thanks.
