### ISSUE TITLE
UNB: Attribute sender is required

### ISSUE THREAD

**Issue by ejudgemeddbase** [nhsconnect/integration-adaptor-lab-results#139]
The following request produces the above error:

UNA:+.? 'UNB+UNOC:3++000000147500001:80+010330:1812+1034++MEDRPT'UNH+1+MEDRPT:0:1:RT:NHS003'BGM+LSR'DTM+137:200103301742:203'S01+01'NAD+PO+G1234552:900++QUENTIN QUICK'SPR+PRO'S01+01'NAD+MR+G1234552:900++QUENTIN QUICK'SPR+PRO'S01+01'NAD+MR+B86123:901'SPR+ORG'S01+01'NAD+SLA+++Clinical chemistry'SPR+DPT'S01+01'NAD+SLA+++ST JAMES?'S UNIVERSITY HOSPITAL'SPR+ORG'S02+02'GIS+N'RFF+SRI:1034/CH6002801B/200103301642'STS++UN'DTM+ISR:200103301642:203'S06+06'ADR++US:1 WEST DENE:LEEDS++LS17 8QT'S07+07'PNA+PAT+5681121828:OPI+++SU:POTTER+FO:KERRY'DTM+329:19690819:102'PDI+2'S16+16'SEQ++1'SPC+TSP+:::PLASMA'RFF+STI:CH6002801B'DTM+SCO:200103300942:203'DTM+SRI:200103301242:203'GIS+N'INV+MQ+44g..:911::Plasma glucose level'RSL+NV+5.9++:::mmol/L'RFF+ASL:1'S20+20'RND+U+3.3+8.8'UNT+42+1'UNZ+1+1034'

**Comment by bartek-sarul** [comment]
According to documentation `UNB` sender field is mandatory
![image](https://user-images.githubusercontent.com/10883492/117158370-a4318680-adbf-11eb-910c-f698e9015ab5.png)

**Comment by ejudgemeddbase** [comment]
Thanks.
