### ISSUE TITLE
Couldn't decode recipient: 000000073300001

### ISSUE THREAD

**Issue by ejudgemeddbase** [nhsconnect/integration-adaptor-lab-results#140]
The following request causes the above error:

UNA:+.? 'UNB+UNOC:3+000000073300001:80+000000147500001:80+010330:1813+1035++MEDRPT++1'UNH+1+MEDRPT:0:1:RT:NHS003'BGM+LSR'DTM+137:200103301743:203'S01+01'NAD+PO+G1234552:900++QUENTIN QUICK'SPR+PRO'S01+01'NAD+MR+G1234552:900++QUENTIN QUICK'SPR+PRO'S01+01'NAD+MR+B86123:901'SPR+ORG'S01+01'NAD+SLA+++Clinical chemistry'SPR+DPT'S01+01'NAD+SLA+++ST JAMES?'S UNIVERSITY HOSPITAL'SPR+ORG'S02+02'GIS+N'RFF+SRI:1035/CH6201101C/200103301643'STS++UN'DTM+ISR:200103301643:203'S06+06'ADR++US:1 WEST DENE:LEEDS++LS17 8QT'S07+07'PNA+PAT+5681121828:OPI+++SU:POTTER+FO:KERRY'DTM+329:19690819:102'PDI+2'S16+16'SEQ++1'SPC+TSP+:::PLASMA'RFF+STI:CH6201101C'DTM+SCO:200103300943:203'DTM+SRI:200103301243:203'GIS+N'INV+MQ+44g..:911::Plasma glucose level'RSL+NV+5.9++:::mmol/L'RFF+ASL:1'S20+20'RND+U+3.3+8.8'UNT+42+1'UNZ+1+1035'

**Comment by bartek-sarul** [comment]
@ejudgemeddbase adaptor is unable to determine recipient `000000073300001` MESH mailbox to be able to send NHSACK to
Check `LAB_RESULTS_MESH_RECIPIENT_MAILBOX_ID_MAPPINGS` environment variable which should contain key=value pairs separated using space char. 
e.g.
`000000073300001=mailbox1 000000147500001=mailbox2`

**Comment by ejudgemeddbase** [comment]
This is fine. Thanks.
