### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: null 	at uk.nhs.digital.nhsconnect.lab.results.model.edifact.FreeTextSegment.fromString(FreeTextSegment.java:44)

### ISSUE THREAD

**Issue by ejudgemeddbase** [nhsconnect/integration-adaptor-lab-results#143]
**Bugs**
The error _java.lang.ArrayIndexOutOfBoundsException: null at uk.nhs.digital.nhsconnect.lab.results.model.edifact.FreeTextSegment.fromString(FreeTextSegment.java:44)_ is produced when the following request is run:

UNA:+.? 'UNB+UNOC:3+000000004400001:80+000000024600002:80+091102:1731+25998++MEDRPT++1++1'UNH+1+MEDRPT:0:1:RT:NHS003'BGM+LSR'DTM+137:200911021044:203'S01+01'NAD+PO+G8705475:900++GENT'SPR+PRO'S01+01'NAD+MR+G8705475:900++GENT'SPR+PRO'S01+01'NAD+MR+D82015:901'SPR+ORG'S01+01'NAD+SLA+C1357930:902++P PRESLAND'SPR+PRO'S01+01'NAD+SLA+++Microbiology'SPR+DPT'S01+01'NAD+SLA+++ST JAMES?'S UNIVERSITY HOSPITAL'SPR+ORG'S02+02'GIS+N'RFF+SRI:9/CH000028B/200910301044'STS++UN'DTM+ISR:200911011044:203'S06+06'S07+07'PNA+PAT+9435547230:OPI+++SU:WAFID+FO:NAQVI'DTM+329:19891126:102'PDI+1'S10+10'CIN+UN'FTX+CID+++Otitis media'S16+16'SEQ++1'SPC+TSP+:::Left ear swab'RFF+STI:CH000028BA'DTM+SCO:200910301044:203'GIS+N'INV+MQ+4I16.:911::Micro, culture & sensitivities'FTX+RIT+++Microscopy'FTX+RIT'FTX+RIT+++Moderate pus cells:Gram negative bacilli ?+'FTX+RIT'FTX+RIT+++Culture'FTX+RIT'FTX+RIT+++1.Haemophilus  influenzae ?+?+?+:2.Staphylococcus aureus ?+'FTX+RIT'FTX+RIT+++Sensitivities'FTX+RIT'FTX+RIT+++                    1 2 3 4 5:Amoxycillin         S R:Trimethoprim        S R:Flucloxacillin      R S:Erythromicin        R S'FTX+RIT'FTX+RIT+++Other bacteria of doubtful significance'RFF+ASL:1'UNT+56+1'UNZ+1+25998'

**Steps to Reproduce**
See the above.

**Expected Behaviour**
To be determined. It's possible that this request is bad (i.e. has an invalid parameter), but it is one we received from Edge (LGNE0801 - Valid - 30 Char Rubric uses ampasand.dat), so thought to check.

**Comment by bartek-sarul** [comment]
Duplicate?
https://github.com/nhsconnect/integration-adaptor-lab-results/issues/145

**Comment by ejudgemeddbase** [comment]
It's a different request, I think.

**Comment by ejudgemeddbase** [comment]
**RETEST 1**
 
**TEST STEPS TO REPRODUCE ISSUE**
 Re-ran request LGNE0801 - Valid - 30 Char Rubric uses ampasand.dat

ACTUAL RESULT
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/82526722/123945927-8f740800-d996-11eb-80ac-0845eb7e6ea6.png)
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/82526722/123945929-900c9e80-d996-11eb-8725-cc5a741722bc.png)
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/82526722/123945930-90a53500-d996-11eb-917f-97f8c0091c92.png)
[143FhirPayload.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6740131/143FhirPayload.txt)

A response was received by the application, and there were no errors in the logs.
 
**Retest 1 PASSED**
 
**Defect 143 Closed**
