### ISSUE TITLE
No laboratory investigation code for 'ZZZ'

### ISSUE THREAD

**Issue by ejudgemeddbase** [nhsconnect/integration-adaptor-lab-results#144]
The following request produces the above error:

UNA:+.? 'UNB+UNOC:3+000000073300001:80+000000147500001:80+030618:0841+2++MEDRPT'UNH+1+MEDRPT:0:1:RT:NHS003'BGM+LSR'DTM+137:200306180841:203'S01+01'NAD+MR+M81023:901'SPR+ORG'S01+01'NAD+PO+G8900249:900++LITCHFIELD JA'SPR+PRO'S01+01'NAD+MR+G8900249:900++LITCHFIELD JA'SPR+PRO'S01+01'NAD+SLA+++HEREFORD'SPR+ORG'S01+01'NAD+SLA+++General Pathology'SPR+DPT'S02+02'GIS+N'RFF+SRI:1-59338288280003'STS++UN'DTM+ISR:200306180800:203'S06+06'RFF+SSI:309925'ADR++US:2 SHERRINGTON DRIVE:HEREFORD++HR4 9XD'S07+07'PNA+PAT++++SU:PICARD+FO:JEANLUC'DTM+329:19900206:102'PDI+2'S10+10'CIN+UN'FTX+CID+++Clinical Details?:'FTX+CID+++NOTE?: Specimen date'S16+16'SEQ++1'SPC+TSP+:::SERUM'RFF+STI:CC093482F'DTM+SCO:20030616:102'DTM+SRI:200306171421:203'GIS+N'INV+MQ+:ZZZ::dodgy header1'SEQ++1'RFF+ASL:1'GIS+N'INV+MQ+44M3.:911::Serum total protein'RSL+NV+79++:::g/L'RFF+ARL:1'S20+20'RND+U+60+80'GIS+N'INV+MQ+44M4.:911::Serum albumin'RSL+NV+35++:::g/L'RFF+ARL:1'S20+20'RND+U+35+50'GIS+N'INV+MQ+44I8.:911::Serum calcium'RSL+NV+2.23++:::mmol/L'RFF+ARL:1'S20+20'RND+U+2.10+2.55'GIS+N'INV+MQ+44IC.:911::Corrected serum calcium level'RSL+NV+2.38++:::mmol/L'RFF+ARL:1'S20+20'RND+U+2.10+2.55'GIS+N'INV+MQ+44I9.:911::Serum inorganic phosphate'RSL+++++OR'FTX+RIT+++U=Unsuitable for analysis'RFF+ARL:1'GIS+N'INV+MQ+44F..:911::Serum alkaline phosphatase'RSL+NV+130++:::iu/L'RFF+ARL:1'S20+20'RND+U+20+450'GIS+N'INV+MQ+44JB.:911::Urea and electrolytes'SEQ++2'RFF+ASL:1'GIS+N'INV+MQ+:ZZZ::dodgy header 2'RSL+NV+3.2++:::mmol/L'RFF+ARL:2'S20+20'RND+U+2.5+7.5'GIS+N'INV+MQ+44I5.:911::Serum sodium'RSL+NV+141++:::mmol/L'RFF+ARL:2'S20+20'RND+U+134+146'GIS+N'INV+MQ+44I4.:911::Serum potassium'FTX+RIT+++U=Unsuitable for analysis'FTX+SPC+++U=Unsuitable,due to delay in delivery.'RFF+ARL:2'GIS+N'INV+MQ+44J3.:911::Serum creatinine'RSL+NV+85++:::umol/L'RFF+ARL:2'S20+20'RND+U+50+120'GIS+N'INV+MQ+44CS.:911::Serum C reactive protein level'RSL+NV+16++:::mg/L+OR'RFF+ASL:1'S20+20'RND+U+1+4'GIS+N'INV+MQ+42R7.:911::Serum iron level'RSL+NV+4++:::umol/L+OR'RFF+ASL:1'S20+20'RND+U+11+29'GIS+N'INV+MQ+42R5.:911::Serum TIBC'RSL+NV+45++:::umol/L+OR'RFF+ASL:1'S20+20'RND+U+49+70'UNT+125+1'UNZ+1+2'

**Comment by bartek-sarul** [comment]
@ejudgemeddbase `INV+MQ+:ZZZ::dodgy header1'` 
`ZZZ` is an invalid coding indicator
Should be `911` for Read2 (NHS002, NHS003) but we also support `921` for SNOMED (NHS004)
![image](https://user-images.githubusercontent.com/10883492/117160909-cf1cda00-adc1-11eb-9791-24eb57f7d37f.png)

**Comment by ejudgemeddbase** [comment]
Thanks.
