### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: null

### ISSUE THREAD

**Issue by ejudgemeddbase** [nhsconnect/integration-adaptor-lab-results#145]
The following request produced the above error:

UNA:+.? 'UNB+UNOC:3+000000073300001:80+000000147500001:80+010330:1752+1014++MEDRPT'UNH+1+MEDRPT:0:1:RT:NHS003'BGM+LSR'DTM+137:200103301722:203'S01+01'NAD+MR+B86123:901'SPR+ORG'S01+01'NAD+MR+G1234545:900++RAY ROLT'SPR+PRO'S01+01'NAD+PO+G1234545:900++RAY ROLT'SPR+PRO'S01+01'NAD+SLA+++ST JAMES?'S UNIVERSITY HOSPITAL'SPR+ORG'S01+01'NAD+SLA+++PATHOLOGY'SPR+DPT'S02+02'GIS+N'RFF+SRI:1014/CH2101201V/200103301622'STS++UN'DTM+ISR:200103301622:203'S06+06'S07+07'PNA+PAT+6764129630:OPI+++SU:WOODLOUSE+FO:ALISTAIR'DTM+329:19110212:102'PDI+1'S16+16'SEQ++1'SPC+TSP+:::BLOOD'DTM+SCO:200103300922:203'DTM+SRI:200103301222:203'GIS+N'INV+MQ+:::RELEASE CHARACTER TEST'FTX+RIT+++Each of the five segments immediately after this one use just the:first of the five free text lines available.'FTX+RIT+++This line ends with 6 colons         - ?:?:?:?:?:?:'FTX+RIT+++This line ends with 3 pluses         - ?+?+?+'FTX+RIT+++This line ends with 4 question marks - ????????'FTX+RIT+++This line ends with 5 apostrophes    - ?'?'?'?'?''FTX+RIT'FTX+RIT+++This segment uses all five free text lines.:Line 2 ends with 5 colons            - ?:?:?:?:?::Line 3 ends with 4 pluses            - ?+?+?+?+:Line 4 ends with 3 question marks    - ??????:Line 5 ends with 2 apostrophes       - ?'?''FTX+RIT'FTX+RIT+++This segment contains apostrophes and text that looks like a segment.:Here are 3 apostrophes and FTX segment data - ?'?'?'FTX?+RIT?+?+?+OK ???''RFF+ASL:1'UNT+46+1'UNZ+1+1014'

**Comment by bartek-sarul** [comment]
I think `FTX` must have some value
![image](https://user-images.githubusercontent.com/10883492/117166872-1063b880-adc7-11eb-9e03-b804228f02cf.png)
