### ISSUE TITLE
java.lang.IllegalArgumentException: No deviating result indicator for 'UN'

### ISSUE THREAD

**Issue by ejudgemeddbase** [nhsconnect/integration-adaptor-lab-results#146]
The following request gives the above error:

UNA:+.? 'UNB+UNOC:3+000000073300001:80+000000147500001:80+010330:1731+2001++MEDRPT'UNH+1+MEDRPT:0:1:RT:NHS003'BGM+LSR'DTM+137:200103301701:203'S01+01'NAD+PO+G1234521:900++Tristan Trotter'SPR+PRO'S01+01'NAD+MR+G1234521:900++Tristan Trotter'SPR+PRO'S01+01'NAD+MR+B86123:901'SPR+ORG'S01+01'NAD+SLA+++Haematology'SPR+DPT'S01+01'NAD+SLA+++ST JAMES?'S UNIVERSITY HOSPITAL'SPR+ORG'S02+02'GIS+N'RFF+SRI:1001/HA1201101A/200103301601'STS++UN'DTM+ISR:200103301601:203'S06+06'ADR++US:1 WEST DENE:LEEDS++LS17 8QT'S07+07'PNA+PAT+5681121828:OPI+++SU:POTTER+FO:KERRY+MI:B+TI:MRS.'DTM+329:19690819:102'PDI+2'S10+10'CIN+UN'FTX+CID+++TIRED ALL THE TIME, LOW Hb'S16+16'SEQ++1'SPC+TSP+:::VENOUS BLOOD'RFF+STI:HA1201101A'DTM+SCO:200103300901:203'DTM+SRI:200103301201:203'GIS+N'INV+MQ+:::Serum ferritin'RSL+NV+101++:::ng/mL+UN'RFF+ASL:1'S20+20'RND+U+10+200'UNT+45+1'UNZ+1+2001'

**Comment by bartek-sarul** [comment]
@ejudgemeddbase `RSL+NV+101++:::ng/mL+UN'` has `deviating result indicator` set to `UN` which is an invalid value
![image](https://user-images.githubusercontent.com/10883492/117159847-e909ed00-adc0-11eb-920d-1417e8d8a4c2.png)
![image](https://user-images.githubusercontent.com/10883492/117159872-ef986480-adc0-11eb-87c3-8c96ef957a5b.png)

**Comment by ejudgemeddbase** [comment]
Thanks.
