### ISSUE TITLE
Specification Validation Error: Missing Code or coding entirely in the Observation (TestResult or TestGroup)

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#147]
**Bugs**
The observation code element is mandatory and all system, code, and display elements must be populated.
![image](https://user-images.githubusercontent.com/2870531/115728838-c3babf00-a37c-11eb-98fb-b9b2b1b3f1ea.png)

![image](https://user-images.githubusercontent.com/2870531/115729089-04b2d380-a37d-11eb-816e-1fd86bea5c01.png)

**To Reproduce**
1. Check for example NHS002-> full_acceptance_with_nhsack.1.fhir.json
2. Look at the Observation, the code missing coding element entirely. 
 (some other missing display, or code of the coding)

or 
1. Check for example NHS002->full_acceptance_without_nhsack.1.fhir.json
2. Look for the Observation in the attached picture
3. The read code is without the Display elements

**Expected behaviors**
must output the coding as per specification, or make exceptions or consider as bad data ??

**Comment by bartek-sarul** [comment]
EDIFACT can give us free text and/or code but this is Read2 for Pathology and SNOMED for Screening
This won't conform profile requirements

**Comment by Kusnaditjung** [comment]
@bartek-sarul no problem ... as it seems it is not possible to entirely conforming to the requirements.. I think it may be worth discussing with NHSD which requirements that the adapter will not comply to and put them in the adapter documentation, so the adapter integration implementer can adjust accordingly.

**Comment by bartek-sarul** [comment]
This has been raised with NHS
