### ISSUE TITLE
Couldn't decode recipient error when setup adaptor with multiple sender to Mailbox ID Mappings

### ISSUE THREAD

**Issue by KGita-md** [nhsconnect/integration-adaptor-lab-results#151]
Description:

With the Pathology Covid Edifact testing , another sender id (110000746500005 ) has been added.
Because of this , updated the LAB_RESULTS_MESH_RECIPIENT_MAILBOX_ID_MAPPINGS to refer values as 000000004400001=C88062GP001 and 110000746500005=C88062GP001.
As we deployed the adaptor to aks cluster , created the configmap from file (mapping.properties)
We see multiline configmap values are being passed to adaptor but when we send edifact request to mesh mailbox, FHIR.json is getting generated at gp outbound queue but there is a issue in getting NHSACK for the request with error as **Couldn't decode recipient.**
When we pass single value to the mapping variable, works fine without any error, Issue is when we have multiple mappings

Test data -
![image](https://user-images.githubusercontent.com/68695717/116999589-7421af00-acfd-11eb-8118-73e42e18085c.png)
![image](https://user-images.githubusercontent.com/68695717/116999634-80a60780-acfd-11eb-9c02-aec707fead87.png)
![image](https://user-images.githubusercontent.com/68695717/116999655-8b609c80-acfd-11eb-9ef5-b2e3800556af.png)
[ps_covid.log](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6420870/ps_covid.log)

Priority - Medium

@michael-kainos @bartek-sarul

**Comment by bartek-sarul** [comment]
set those k=v all in new line with space as separator so change this
```
000000004400001=C88062GP001
110000746500005=C88062GP001
```
to this
```
000000004400001=C88062GP001 110000746500005=C88062GP001
```

**Comment by KGita-md** [comment]
Added all required mappings to single line separated by single space. Executed request for each type with azure pipeline. Issue is fixed now. Getting NHSACK for messages as expected.

![image](https://user-images.githubusercontent.com/68695717/117133984-9cbfac80-adc2-11eb-97c8-6f9a14f1c664.png)
[ps_log_505.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6426708/ps_log_505.txt)
