### ISSUE TITLE
FHIR field assignment error: EDIFACT delimiter get populated in the coded value display

### ISSUE THREAD

**Issue by Kusnaditjung** [nhsconnect/integration-adaptor-lab-results#152]
**Bugs**
Some of the coded value population get mixed with the EDIFACT delimiter
see example  https://github.com/nhsconnect/integration-adaptor-lab-results/blob/main/src/intTest/resources/success_uat_data/NHS004/screening_full_acceptance_with_nhsack.1.fhir.json

in this text:
                      {
                            "system": "http://snomed.info/sct",
                            "code": "368481000000103",
                            "display": "BCS?:FOB result"
                        }

**Step to reproduce**
See example above

**Expected behaviors**
delimiter character should not be populated.

**Comment by jhoey-med** [comment]
### RETEST 1
 
**TEST STEPS TO REPRODUCE ISSUE**

Resend screening_full_acceptance_with_nhsack.edifact.dat and inspect FHIR response

**ACTUAL RESULT**
 
EDIFACT delimiter is not present in 'display' FHIR element.

Please see screenshots attached.

![image](https://user-images.githubusercontent.com/81386191/124158912-6afd5600-da92-11eb-81c2-bebf788e1088.png)

![image](https://user-images.githubusercontent.com/81386191/124158941-73559100-da92-11eb-93c1-3b8bd6c10db0.png)

![image](https://user-images.githubusercontent.com/81386191/124158975-7badcc00-da92-11eb-88fc-572269145bca.png)

![image](https://user-images.githubusercontent.com/81386191/124159006-85373400-da92-11eb-8b08-0e9e9d0bcd63.png)

[NHS004_screening_full_acceptance_with_nhsack.edifact.dat FHIR payload txt.txt](https://github.com/nhsconnect/integration-adaptor-lab-results/files/6749667/NHS004_screening_full_acceptance_with_nhsack.edifact.dat.FHIR.payload.txt.txt)


Retest 1 **PASSED**
 
Defect 152 Closed
